apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: mediacms
spec:
  selector:
    matchLabels:
      app: celery-beat
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery-beat
        image: hoangbaoan1901/mediacms
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: ENABLE_UWSGI
          value: "no"
        - name: ENABLE_NGINX
          value: "no"
        - name: ENABLE_CELERY_BEAT
          value: "yes" 
        - name: ENABLE_MIGRATIONS
          value: "no"
        - name: ENABLE_CELERY_SHORT
          value: "no"
        - name: ENABLE_CELERY_LONG
          value: "no"   
 