kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mediacms
  namespace: mediacms
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi

  storageClassName: filestore-rwm