apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: db-pvc
  namespace: mediacms
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
